apiVersion: apps/v1
kind: Deployment
metadata:
  name: fdapn-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fdapn
  template:
    metadata:
      labels:
        app: fdapn
    spec:
      containers:
        - name: fdapn
          image: sb2crest/fdapn-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://localhost:5432/fdapn"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "root"
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: "update"
      restartPolicy: Always
